CREATE TABLE learning_activities (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    correction_id bigint UNIQUE REFERENCES corrections(id) ON DELETE CASCADE,
    quiz_attempt_id bigint UNIQUE REFERENCES quiz_attempts(id) ON DELETE CASCADE,
    occurred_at timestamp with time zone NOT NULL,
    CONSTRAINT learning_activity_one_source CHECK (num_nonnulls(correction_id, quiz_attempt_id) = 1)
);

CREATE INDEX learning_activities_user_time_idx ON learning_activities(user_id, occurred_at);

INSERT INTO learning_activities (user_id, correction_id, occurred_at)
SELECT user_id, id, created_at FROM corrections;

INSERT INTO learning_activities (user_id, quiz_attempt_id, occurred_at)
SELECT user_id, id, created_at FROM quiz_attempts;
