ALTER TABLE users ADD COLUMN id_new bigint;
ALTER TABLE accounts ADD COLUMN id_new bigint;
ALTER TABLE auth_sessions ADD COLUMN id_new bigint;
ALTER TABLE verifications ADD COLUMN id_new bigint;
ALTER TABLE corrections ADD COLUMN id_new bigint;
ALTER TABLE correction_mistakes ADD COLUMN id_new bigint;
ALTER TABLE quiz_questions ADD COLUMN id_new bigint;
ALTER TABLE quiz_choices ADD COLUMN id_new bigint;
ALTER TABLE quiz_attempts ADD COLUMN id_new bigint;
ALTER TABLE user_identities ADD COLUMN id_new bigint;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM users
)
UPDATE users target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM accounts
)
UPDATE accounts target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM auth_sessions
)
UPDATE auth_sessions target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM verifications
)
UPDATE verifications target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM corrections
)
UPDATE corrections target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM correction_mistakes
)
UPDATE correction_mistakes target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM quiz_questions
)
UPDATE quiz_questions target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM quiz_choices
)
UPDATE quiz_choices target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM quiz_attempts
)
UPDATE quiz_attempts target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

WITH numbered AS (
    SELECT id, row_number() OVER (ORDER BY id)::bigint AS id_new
    FROM user_identities
)
UPDATE user_identities target
SET id_new = numbered.id_new
FROM numbered
WHERE target.id = numbered.id;

ALTER TABLE users
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE accounts
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE auth_sessions
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE verifications
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE corrections
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE correction_mistakes
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE quiz_questions
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE quiz_choices
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE quiz_attempts
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE user_identities
    ALTER COLUMN id_new SET NOT NULL,
    ALTER COLUMN id_new ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('users', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM users;
SELECT setval(
    pg_get_serial_sequence('accounts', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM accounts;
SELECT setval(
    pg_get_serial_sequence('auth_sessions', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM auth_sessions;
SELECT setval(
    pg_get_serial_sequence('verifications', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM verifications;
SELECT setval(
    pg_get_serial_sequence('corrections', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM corrections;
SELECT setval(
    pg_get_serial_sequence('correction_mistakes', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM correction_mistakes;
SELECT setval(
    pg_get_serial_sequence('quiz_questions', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM quiz_questions;
SELECT setval(
    pg_get_serial_sequence('quiz_choices', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM quiz_choices;
SELECT setval(
    pg_get_serial_sequence('quiz_attempts', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM quiz_attempts;
SELECT setval(
    pg_get_serial_sequence('user_identities', 'id_new'),
    COALESCE(max(id_new), 1),
    max(id_new) IS NOT NULL
)
FROM user_identities;

ALTER TABLE accounts ADD COLUMN user_id_new bigint;
ALTER TABLE auth_sessions ADD COLUMN user_id_new bigint;
ALTER TABLE daily_usage ADD COLUMN user_id_new bigint;
ALTER TABLE corrections ADD COLUMN user_id_new bigint;
ALTER TABLE user_tag_stats ADD COLUMN user_id_new bigint;
ALTER TABLE user_identities ADD COLUMN user_id_new bigint;
ALTER TABLE correction_mistakes ADD COLUMN correction_id_new bigint;
ALTER TABLE quiz_questions ADD COLUMN supersedes_quiz_id_new bigint;
ALTER TABLE quiz_choices ADD COLUMN quiz_question_id_new bigint;
ALTER TABLE quiz_attempts
    ADD COLUMN user_id_new bigint,
    ADD COLUMN quiz_question_id_new bigint,
    ADD COLUMN selected_choice_id_new bigint;

UPDATE accounts child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE auth_sessions child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE daily_usage child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE corrections child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE user_tag_stats child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE user_identities child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE correction_mistakes child
SET correction_id_new = parent.id_new
FROM corrections parent
WHERE child.correction_id = parent.id;

UPDATE quiz_questions child
SET supersedes_quiz_id_new = parent.id_new
FROM quiz_questions parent
WHERE child.supersedes_quiz_id = parent.id;

UPDATE quiz_choices child
SET quiz_question_id_new = parent.id_new
FROM quiz_questions parent
WHERE child.quiz_question_id = parent.id;

UPDATE quiz_attempts child
SET user_id_new = parent.id_new
FROM users parent
WHERE child.user_id = parent.id;

UPDATE quiz_attempts child
SET quiz_question_id_new = parent.id_new
FROM quiz_questions parent
WHERE child.quiz_question_id = parent.id;

UPDATE quiz_attempts child
SET selected_choice_id_new = parent.id_new
FROM quiz_choices parent
WHERE child.selected_choice_id = parent.id;

ALTER TABLE accounts ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE auth_sessions ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE daily_usage ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE corrections ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE user_tag_stats ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE user_identities ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE correction_mistakes ALTER COLUMN correction_id_new SET NOT NULL;
ALTER TABLE quiz_choices ALTER COLUMN quiz_question_id_new SET NOT NULL;
ALTER TABLE quiz_attempts
    ALTER COLUMN user_id_new SET NOT NULL,
    ALTER COLUMN quiz_question_id_new SET NOT NULL,
    ALTER COLUMN selected_choice_id_new SET NOT NULL;

DROP INDEX quiz_attempts_user_question_created_idx;
DROP INDEX quiz_questions_active_fingerprint_unique;
DROP INDEX quiz_questions_revision_target_unique;
DROP INDEX quiz_choices_one_correct_per_question_unique;
DROP INDEX user_identities_user_id_idx;

ALTER TABLE accounts
    DROP CONSTRAINT accounts_pkey,
    DROP CONSTRAINT accounts_user_id_users_id_fk;
ALTER TABLE auth_sessions
    DROP CONSTRAINT auth_sessions_pkey,
    DROP CONSTRAINT auth_sessions_user_id_users_id_fk;
ALTER TABLE verifications
    DROP CONSTRAINT verifications_pkey;
ALTER TABLE daily_usage
    DROP CONSTRAINT daily_usage_user_id_usage_date_pk,
    DROP CONSTRAINT daily_usage_user_id_users_id_fk;
ALTER TABLE correction_mistakes
    DROP CONSTRAINT correction_mistakes_correction_id_corrections_id_fk,
    DROP CONSTRAINT correction_mistakes_pkey;
ALTER TABLE corrections
    DROP CONSTRAINT corrections_user_id_users_id_fk,
    DROP CONSTRAINT corrections_pkey;
ALTER TABLE user_tag_stats
    DROP CONSTRAINT user_tag_stats_user_id_tag_pk,
    DROP CONSTRAINT user_tag_stats_user_id_users_id_fk;
ALTER TABLE quiz_attempts
    DROP CONSTRAINT quiz_attempts_pkey,
    DROP CONSTRAINT quiz_attempts_user_id_users_id_fk,
    DROP CONSTRAINT quiz_attempts_quiz_question_id_quiz_questions_id_fk,
    DROP CONSTRAINT quiz_attempts_question_selected_choice_fk;
ALTER TABLE quiz_choices
    DROP CONSTRAINT quiz_choices_pkey,
    DROP CONSTRAINT quiz_choices_quiz_question_id_quiz_questions_id_fk,
    DROP CONSTRAINT quiz_choices_question_sort_order_unique,
    DROP CONSTRAINT quiz_choices_question_id_id_unique;
ALTER TABLE quiz_questions
    DROP CONSTRAINT quiz_questions_supersedes_quiz_id_quiz_questions_id_fk,
    DROP CONSTRAINT quiz_questions_not_self_superseding_check,
    DROP CONSTRAINT quiz_questions_pkey;
ALTER TABLE user_identities
    DROP CONSTRAINT user_identities_pkey,
    DROP CONSTRAINT user_identities_user_id_users_id_fk;
ALTER TABLE users DROP CONSTRAINT users_pkey;

ALTER TABLE accounts DROP COLUMN id, DROP COLUMN user_id;
ALTER TABLE auth_sessions DROP COLUMN id, DROP COLUMN user_id;
ALTER TABLE verifications DROP COLUMN id;
ALTER TABLE daily_usage DROP COLUMN user_id;
ALTER TABLE corrections DROP COLUMN id, DROP COLUMN user_id;
ALTER TABLE correction_mistakes DROP COLUMN id, DROP COLUMN correction_id;
ALTER TABLE user_tag_stats DROP COLUMN user_id;
ALTER TABLE quiz_attempts
    DROP COLUMN id,
    DROP COLUMN user_id,
    DROP COLUMN quiz_question_id,
    DROP COLUMN selected_choice_id;
ALTER TABLE quiz_choices DROP COLUMN id, DROP COLUMN quiz_question_id;
ALTER TABLE quiz_questions DROP COLUMN id, DROP COLUMN supersedes_quiz_id;
ALTER TABLE user_identities DROP COLUMN id, DROP COLUMN user_id;
ALTER TABLE users DROP COLUMN id;

ALTER TABLE users RENAME COLUMN id_new TO id;
ALTER TABLE accounts RENAME COLUMN id_new TO id;
ALTER TABLE accounts RENAME COLUMN user_id_new TO user_id;
ALTER TABLE auth_sessions RENAME COLUMN id_new TO id;
ALTER TABLE auth_sessions RENAME COLUMN user_id_new TO user_id;
ALTER TABLE verifications RENAME COLUMN id_new TO id;
ALTER TABLE daily_usage RENAME COLUMN user_id_new TO user_id;
ALTER TABLE corrections RENAME COLUMN id_new TO id;
ALTER TABLE corrections RENAME COLUMN user_id_new TO user_id;
ALTER TABLE correction_mistakes RENAME COLUMN id_new TO id;
ALTER TABLE correction_mistakes RENAME COLUMN correction_id_new TO correction_id;
ALTER TABLE user_tag_stats RENAME COLUMN user_id_new TO user_id;
ALTER TABLE quiz_questions RENAME COLUMN id_new TO id;
ALTER TABLE quiz_questions RENAME COLUMN supersedes_quiz_id_new TO supersedes_quiz_id;
ALTER TABLE quiz_choices RENAME COLUMN id_new TO id;
ALTER TABLE quiz_choices RENAME COLUMN quiz_question_id_new TO quiz_question_id;
ALTER TABLE quiz_attempts RENAME COLUMN id_new TO id;
ALTER TABLE quiz_attempts RENAME COLUMN user_id_new TO user_id;
ALTER TABLE quiz_attempts RENAME COLUMN quiz_question_id_new TO quiz_question_id;
ALTER TABLE quiz_attempts RENAME COLUMN selected_choice_id_new TO selected_choice_id;
ALTER TABLE user_identities RENAME COLUMN id_new TO id;
ALTER TABLE user_identities RENAME COLUMN user_id_new TO user_id;

ALTER SEQUENCE users_id_new_seq RENAME TO users_id_seq;
ALTER SEQUENCE accounts_id_new_seq RENAME TO accounts_id_seq;
ALTER SEQUENCE auth_sessions_id_new_seq RENAME TO auth_sessions_id_seq;
ALTER SEQUENCE verifications_id_new_seq RENAME TO verifications_id_seq;
ALTER SEQUENCE corrections_id_new_seq RENAME TO corrections_id_seq;
ALTER SEQUENCE correction_mistakes_id_new_seq RENAME TO correction_mistakes_id_seq;
ALTER SEQUENCE quiz_questions_id_new_seq RENAME TO quiz_questions_id_seq;
ALTER SEQUENCE quiz_choices_id_new_seq RENAME TO quiz_choices_id_seq;
ALTER SEQUENCE quiz_attempts_id_new_seq RENAME TO quiz_attempts_id_seq;
ALTER SEQUENCE user_identities_id_new_seq RENAME TO user_identities_id_seq;

ALTER TABLE users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id),
    ADD CONSTRAINT accounts_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id),
    ADD CONSTRAINT auth_sessions_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE verifications
    ADD CONSTRAINT verifications_pkey PRIMARY KEY (id);
ALTER TABLE daily_usage
    ADD CONSTRAINT daily_usage_user_id_usage_date_pk PRIMARY KEY (user_id, usage_date),
    ADD CONSTRAINT daily_usage_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE corrections
    ADD CONSTRAINT corrections_pkey PRIMARY KEY (id),
    ADD CONSTRAINT corrections_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE correction_mistakes
    ADD CONSTRAINT correction_mistakes_pkey PRIMARY KEY (id),
    ADD CONSTRAINT correction_mistakes_correction_id_corrections_id_fk
        FOREIGN KEY (correction_id) REFERENCES corrections (id) ON DELETE CASCADE;
ALTER TABLE user_tag_stats
    ADD CONSTRAINT user_tag_stats_user_id_tag_pk PRIMARY KEY (user_id, tag),
    ADD CONSTRAINT user_tag_stats_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
ALTER TABLE quiz_questions
    ADD CONSTRAINT quiz_questions_pkey PRIMARY KEY (id),
    ADD CONSTRAINT quiz_questions_supersedes_quiz_id_quiz_questions_id_fk
        FOREIGN KEY (supersedes_quiz_id) REFERENCES quiz_questions (id),
    ADD CONSTRAINT quiz_questions_not_self_superseding_check
        CHECK (supersedes_quiz_id IS NULL OR supersedes_quiz_id <> id);
ALTER TABLE quiz_choices
    ADD CONSTRAINT quiz_choices_pkey PRIMARY KEY (id),
    ADD CONSTRAINT quiz_choices_quiz_question_id_quiz_questions_id_fk
        FOREIGN KEY (quiz_question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE,
    ADD CONSTRAINT quiz_choices_question_sort_order_unique
        UNIQUE (quiz_question_id, sort_order),
    ADD CONSTRAINT quiz_choices_question_id_id_unique
        UNIQUE (quiz_question_id, id);
ALTER TABLE quiz_attempts
    ADD CONSTRAINT quiz_attempts_pkey PRIMARY KEY (id),
    ADD CONSTRAINT quiz_attempts_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    ADD CONSTRAINT quiz_attempts_quiz_question_id_quiz_questions_id_fk
        FOREIGN KEY (quiz_question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE,
    ADD CONSTRAINT quiz_attempts_question_selected_choice_fk
        FOREIGN KEY (quiz_question_id, selected_choice_id)
        REFERENCES quiz_choices (quiz_question_id, id);
ALTER TABLE user_identities
    ADD CONSTRAINT user_identities_pkey PRIMARY KEY (id),
    ADD CONSTRAINT user_identities_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

CREATE UNIQUE INDEX quiz_questions_active_fingerprint_unique
    ON quiz_questions (content_fingerprint)
    WHERE status = 'approved'
       OR (status = 'draft' AND supersedes_quiz_id IS NULL);
CREATE UNIQUE INDEX quiz_questions_revision_target_unique
    ON quiz_questions (supersedes_quiz_id)
    WHERE status = 'draft'
      AND supersedes_quiz_id IS NOT NULL;
CREATE UNIQUE INDEX quiz_choices_one_correct_per_question_unique
    ON quiz_choices (quiz_question_id)
    WHERE is_correct;
CREATE INDEX quiz_attempts_user_question_created_idx
    ON quiz_attempts (user_id, quiz_question_id, created_at);
CREATE INDEX user_identities_user_id_idx
    ON user_identities (user_id);
