CREATE TABLE usage_counters (
    user_id bigint NOT NULL,
    usage_date date NOT NULL,
    feature text NOT NULL,
    units bigint DEFAULT 0 NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT usage_counters_user_date_feature_pk
        PRIMARY KEY (user_id, usage_date, feature),
    CONSTRAINT usage_counters_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT usage_counters_feature_not_blank_check
        CHECK (feature <> ''),
    CONSTRAINT usage_counters_units_non_negative_check
        CHECK (units >= 0)
);

INSERT INTO usage_counters (user_id, usage_date, feature, units, updated_at)
SELECT user_id, usage_date, 'correction', correction_count, updated_at
FROM daily_usage
UNION ALL
SELECT user_id, usage_date, 'ocr', ocr_count, updated_at
FROM daily_usage;

CREATE TABLE usage_reservations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    usage_date date NOT NULL,
    feature text NOT NULL,
    units bigint NOT NULL,
    status text DEFAULT 'reserved' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT usage_reservations_user_id_users_id_fk
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT usage_reservations_feature_not_blank_check
        CHECK (feature <> ''),
    CONSTRAINT usage_reservations_units_positive_check
        CHECK (units > 0),
    CONSTRAINT usage_reservations_status_check
        CHECK (status IN ('reserved', 'committed', 'released'))
);

CREATE INDEX usage_reservations_user_date_feature_idx
    ON usage_reservations (user_id, usage_date, feature);

DROP TABLE daily_usage;
