CREATE TABLE quiz_learning_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    quiz_question_id bigint,
    quiz_type text NOT NULL,
    tag text NOT NULL,
    target_key text NOT NULL,
    target_digest character(64) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT quiz_learning_targets_quiz_question_id_fk
        FOREIGN KEY (quiz_question_id) REFERENCES quiz_questions (id) ON DELETE SET NULL,
    CONSTRAINT quiz_learning_targets_type_check
        CHECK (quiz_type IN ('grammar', 'vocabulary')),
    CONSTRAINT quiz_learning_targets_key_nonblank_check
        CHECK (btrim(target_key) <> ''),
    CONSTRAINT quiz_learning_targets_digest_check
        CHECK (target_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT quiz_learning_targets_identity_unique
        UNIQUE (quiz_type, tag, target_digest)
);

CREATE INDEX quiz_learning_targets_quiz_question_id_idx
    ON quiz_learning_targets (quiz_question_id);

WITH existing_targets AS (
    SELECT
        question.id AS quiz_question_id,
        question.quiz_type,
        question.tag,
        CASE
            WHEN question.quiz_type = 'vocabulary'
                THEN lower(regexp_replace(btrim(normalize(correct_choice.choice_text, NFC)), '[[:space:]]+', ' ', 'g'))
            WHEN question.tag IN ('sentence_order', 'unnatural')
                THEN lower(regexp_replace(btrim(normalize(correct_choice.choice_text, NFC)), '[[:space:]]+', ' ', 'g'))
            ELSE
                lower(regexp_replace(btrim(normalize(question.sentence_ko, NFC)), '[[:space:]]+', ' ', 'g'))
                || chr(31)
                || lower(regexp_replace(btrim(normalize(correct_choice.choice_text, NFC)), '[[:space:]]+', ' ', 'g'))
        END AS target_key,
        question.created_at
    FROM quiz_questions question
    JOIN quiz_choices correct_choice
      ON correct_choice.quiz_question_id = question.id
     AND correct_choice.is_correct = true
), digested_targets AS (
    SELECT
        quiz_question_id,
        quiz_type,
        tag,
        target_key,
        encode(sha256(convert_to(target_key, 'UTF8')), 'hex') AS target_digest,
        created_at
    FROM existing_targets
), deduplicated_targets AS (
    SELECT DISTINCT ON (quiz_type, tag, target_digest)
        quiz_question_id,
        quiz_type,
        tag,
        target_key,
        target_digest,
        created_at
    FROM digested_targets
    ORDER BY quiz_type, tag, target_digest, created_at, quiz_question_id
)
INSERT INTO quiz_learning_targets (
    quiz_question_id,
    quiz_type,
    tag,
    target_key,
    target_digest,
    created_at
)
SELECT
    quiz_question_id,
    quiz_type,
    tag,
    target_key,
    target_digest,
    created_at
FROM deduplicated_targets;

CREATE TABLE vocabulary_targets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    difficulty text NOT NULL,
    word_ko text NOT NULL,
    normalized_word text NOT NULL,
    target_digest character(64) NOT NULL,
    reservation_key text,
    reserved_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT vocabulary_targets_difficulty_check
        CHECK (difficulty IN ('beginner', 'lower_intermediate', 'intermediate')),
    CONSTRAINT vocabulary_targets_word_nonblank_check
        CHECK (btrim(word_ko) <> '' AND char_length(word_ko) <= 50),
    CONSTRAINT vocabulary_targets_normalized_word_nonblank_check
        CHECK (btrim(normalized_word) <> '' AND char_length(normalized_word) <= 50),
    CONSTRAINT vocabulary_targets_digest_check
        CHECK (target_digest ~ '^[0-9a-f]{64}$'),
    CONSTRAINT vocabulary_targets_reservation_check
        CHECK (
            (reservation_key IS NULL AND reserved_at IS NULL)
            OR (
                reservation_key IS NOT NULL
                AND char_length(reservation_key) BETWEEN 1 AND 100
                AND reserved_at IS NOT NULL
            )
        ),
    CONSTRAINT vocabulary_targets_normalized_word_unique
        UNIQUE (normalized_word),
    CONSTRAINT vocabulary_targets_digest_unique
        UNIQUE (target_digest)
);

CREATE INDEX vocabulary_targets_selection_idx
    ON vocabulary_targets (difficulty, id);

INSERT INTO vocabulary_targets (difficulty, word_ko, normalized_word, target_digest)
SELECT
    seed.difficulty,
    seed.word_ko,
    normalized.normalized_word,
    encode(sha256(convert_to(normalized.normalized_word, 'UTF8')), 'hex')
FROM (
    VALUES
        ('beginner', '도서관'),
        ('beginner', '선생님'),
        ('beginner', '학생'),
        ('beginner', '학교'),
        ('beginner', '시장'),
        ('beginner', '병원'),
        ('beginner', '약국'),
        ('beginner', '식당'),
        ('beginner', '자동차'),
        ('beginner', '커피'),
        ('beginner', '가족'),
        ('beginner', '어머니'),
        ('beginner', '아버지'),
        ('beginner', '부모님'),
        ('beginner', '친구'),
        ('beginner', '사람'),
        ('beginner', '아이'),
        ('beginner', '남자'),
        ('beginner', '여자'),
        ('beginner', '집'),
        ('beginner', '방'),
        ('beginner', '회사'),
        ('beginner', '은행'),
        ('beginner', '우체국'),
        ('beginner', '공원'),
        ('beginner', '역'),
        ('beginner', '공항'),
        ('beginner', '가게'),
        ('beginner', '카페'),
        ('beginner', '화장실'),
        ('beginner', '책'),
        ('beginner', '공책'),
        ('beginner', '연필'),
        ('beginner', '가방'),
        ('beginner', '의자'),
        ('beginner', '책상'),
        ('beginner', '문'),
        ('beginner', '창문'),
        ('beginner', '전화'),
        ('beginner', '컴퓨터'),
        ('beginner', '신발'),
        ('beginner', '옷'),
        ('beginner', '우산'),
        ('beginner', '물'),
        ('beginner', '밥'),
        ('beginner', '빵'),
        ('beginner', '우유'),
        ('beginner', '사과'),
        ('beginner', '바나나'),
        ('beginner', '김치'),
        ('beginner', '고기'),
        ('beginner', '과일'),
        ('beginner', '채소'),
        ('beginner', '음식'),
        ('beginner', '오늘'),
        ('beginner', '내일'),
        ('beginner', '어제'),
        ('beginner', '지금'),
        ('beginner', '아침'),
        ('beginner', '점심'),
        ('beginner', '저녁'),
        ('beginner', '밤'),
        ('beginner', '주말'),
        ('beginner', '시간'),
        ('beginner', '가다'),
        ('beginner', '오다'),
        ('beginner', '보다'),
        ('beginner', '읽다'),
        ('beginner', '쓰다'),
        ('beginner', '먹다'),
        ('beginner', '마시다'),
        ('beginner', '자다'),
        ('beginner', '공부하다'),
        ('beginner', '일하다'),
        ('beginner', '크다'),
        ('beginner', '작다'),
        ('beginner', '좋다'),
        ('beginner', '많다'),
        ('beginner', '덥다'),
        ('beginner', '춥다'),
        ('beginner', '차갑다'),
        ('lower_intermediate', '동료'),
        ('lower_intermediate', '이웃'),
        ('lower_intermediate', '손님'),
        ('lower_intermediate', '직원'),
        ('lower_intermediate', '사장'),
        ('lower_intermediate', '회의'),
        ('lower_intermediate', '약속'),
        ('lower_intermediate', '일정'),
        ('lower_intermediate', '여행'),
        ('lower_intermediate', '예약'),
        ('lower_intermediate', '표'),
        ('lower_intermediate', '지하철'),
        ('lower_intermediate', '버스정류장'),
        ('lower_intermediate', '교통'),
        ('lower_intermediate', '운전'),
        ('lower_intermediate', '길'),
        ('lower_intermediate', '거리'),
        ('lower_intermediate', '건물'),
        ('lower_intermediate', '아파트'),
        ('lower_intermediate', '엘리베이터'),
        ('lower_intermediate', '계단'),
        ('lower_intermediate', '주방'),
        ('lower_intermediate', '거실'),
        ('lower_intermediate', '냉장고'),
        ('lower_intermediate', '세탁기'),
        ('lower_intermediate', '에어컨'),
        ('lower_intermediate', '청소'),
        ('lower_intermediate', '빨래'),
        ('lower_intermediate', '요리'),
        ('lower_intermediate', '주문'),
        ('lower_intermediate', '계산'),
        ('lower_intermediate', '가격'),
        ('lower_intermediate', '할인'),
        ('lower_intermediate', '영수증'),
        ('lower_intermediate', '현금'),
        ('lower_intermediate', '카드'),
        ('lower_intermediate', '통장'),
        ('lower_intermediate', '월급'),
        ('lower_intermediate', '직업'),
        ('lower_intermediate', '취미'),
        ('lower_intermediate', '운동'),
        ('lower_intermediate', '산책'),
        ('lower_intermediate', '등산'),
        ('lower_intermediate', '수영'),
        ('lower_intermediate', '건강'),
        ('lower_intermediate', '감기'),
        ('lower_intermediate', '약'),
        ('lower_intermediate', '진료'),
        ('lower_intermediate', '증상'),
        ('lower_intermediate', '날씨'),
        ('lower_intermediate', '계절'),
        ('lower_intermediate', '봄'),
        ('lower_intermediate', '여름'),
        ('lower_intermediate', '가을'),
        ('lower_intermediate', '겨울'),
        ('lower_intermediate', '비'),
        ('lower_intermediate', '눈'),
        ('lower_intermediate', '바람'),
        ('lower_intermediate', '계획'),
        ('lower_intermediate', '경험'),
        ('lower_intermediate', '방법'),
        ('lower_intermediate', '이유'),
        ('lower_intermediate', '결과'),
        ('lower_intermediate', '실수'),
        ('lower_intermediate', '문제'),
        ('lower_intermediate', '기회'),
        ('lower_intermediate', '준비하다'),
        ('lower_intermediate', '시작하다'),
        ('lower_intermediate', '끝나다'),
        ('lower_intermediate', '기다리다'),
        ('lower_intermediate', '도착하다'),
        ('lower_intermediate', '출발하다'),
        ('lower_intermediate', '이용하다'),
        ('lower_intermediate', '신청하다'),
        ('lower_intermediate', '선택하다'),
        ('lower_intermediate', '설명하다'),
        ('lower_intermediate', '기억하다'),
        ('lower_intermediate', '잊어버리다'),
        ('lower_intermediate', '필요하다'),
        ('lower_intermediate', '편하다'),
        ('lower_intermediate', '불편하다'),
        ('lower_intermediate', '안전하다'),
        ('lower_intermediate', '위험하다'),
        ('lower_intermediate', '바쁘다'),
        ('lower_intermediate', '한가하다'),
        ('intermediate', '관계'),
        ('intermediate', '갈등'),
        ('intermediate', '신뢰'),
        ('intermediate', '책임'),
        ('intermediate', '태도'),
        ('intermediate', '습관'),
        ('intermediate', '관심'),
        ('intermediate', '의견'),
        ('intermediate', '주장'),
        ('intermediate', '판단'),
        ('intermediate', '결정'),
        ('intermediate', '목표'),
        ('intermediate', '노력'),
        ('intermediate', '성과'),
        ('intermediate', '실패'),
        ('intermediate', '성공'),
        ('intermediate', '변화'),
        ('intermediate', '발전'),
        ('intermediate', '영향'),
        ('intermediate', '원인'),
        ('intermediate', '해결'),
        ('intermediate', '상황'),
        ('intermediate', '조건'),
        ('intermediate', '기준'),
        ('intermediate', '차이'),
        ('intermediate', '공통점'),
        ('intermediate', '장점'),
        ('intermediate', '단점'),
        ('intermediate', '가능성'),
        ('intermediate', '필요성'),
        ('intermediate', '중요성'),
        ('intermediate', '사회'),
        ('intermediate', '문화'),
        ('intermediate', '전통'),
        ('intermediate', '세대'),
        ('intermediate', '환경'),
        ('intermediate', '자원'),
        ('intermediate', '경제'),
        ('intermediate', '소비'),
        ('intermediate', '생산'),
        ('intermediate', '기술'),
        ('intermediate', '정보'),
        ('intermediate', '자료'),
        ('intermediate', '연구'),
        ('intermediate', '교육'),
        ('intermediate', '정책'),
        ('intermediate', '제도'),
        ('intermediate', '법률'),
        ('intermediate', '권리'),
        ('intermediate', '의무'),
        ('intermediate', '지역'),
        ('intermediate', '국제'),
        ('intermediate', '협력'),
        ('intermediate', '경쟁'),
        ('intermediate', '의사소통'),
        ('intermediate', '감정'),
        ('intermediate', '스트레스'),
        ('intermediate', '만족'),
        ('intermediate', '불만'),
        ('intermediate', '존중'),
        ('intermediate', '배려'),
        ('intermediate', '이해'),
        ('intermediate', '오해'),
        ('intermediate', '표현'),
        ('intermediate', '의미'),
        ('intermediate', '가치'),
        ('intermediate', '역할'),
        ('intermediate', '과정'),
        ('intermediate', '목적'),
        ('intermediate', '효과'),
        ('intermediate', '관리'),
        ('intermediate', '참여하다'),
        ('intermediate', '포함하다'),
        ('intermediate', '발생하다'),
        ('intermediate', '증가하다'),
        ('intermediate', '감소하다'),
        ('intermediate', '개선하다'),
        ('intermediate', '유지하다'),
        ('intermediate', '적용하다'),
        ('intermediate', '비교하다'),
        ('intermediate', '분석하다'),
        ('intermediate', '예상하다'),
        ('intermediate', '인정하다'),
        ('intermediate', '강조하다'),
        ('intermediate', '적절하다'),
        ('intermediate', '다양하다'),
        ('intermediate', '복잡하다'),
        ('intermediate', '긍정적이다'),
        ('intermediate', '부정적이다')
) AS seed(difficulty, word_ko)
CROSS JOIN LATERAL (
    SELECT lower(
        regexp_replace(btrim(normalize(seed.word_ko, NFC)), '[[:space:]]+', ' ', 'g')
    ) AS normalized_word
) normalized;
